// The ORCHESTRATOR (doc 06). The five small services above it each do one job; this
// file runs them in order, keeps the row's status honest, and makes sure the caller
// is told what happened - whichever way it ends.
//
//   startEvaluation()  the synchronous half. Checks the job exists, stores the file,
//                      creates the row, and hands the id back so the controller can
//                      answer 202. Fast, and it never calls the LLM.
//   runPipeline()      the background half. parse -> extract -> match -> score ->
//                      store -> webhook.
//
// The split is the whole point of the async design: the pipeline takes seconds
// (two LLM calls), and nobody should hold an HTTP connection open for that (doc 05).
const jobRepository = require('../repositories/jobRepository');
const resumeRepository = require('../repositories/resumeRepository');
const evaluationRepository = require('../repositories/evaluationRepository');
const parseService = require('./parseService');
const extractionService = require('./extractionService');
const matchingService = require('./matchingService');
const scoringService = require('./scoringService');
const webhookService = require('./webhookService');
const fileStorage = require('../utils/fileStorage');
const config = require('../config/env');
const { NotFoundError, PipelineError, FAILURE_REASONS } = require('../utils/errors');

/**
 * The background runs currently in flight, id -> promise.
 *
 * Fire-and-forget work still has to be waitable by SOMETHING, or a graceful
 * shutdown would kill half-finished evaluations and a test could never know when to
 * look at the result. This is that handle. Entries remove themselves when they settle.
 */
const inFlight = new Map();

/** Wait for the background work to finish - used by a graceful shutdown, and by tests. */
async function awaitPendingRuns() {
  while (inFlight.size > 0) {
    await Promise.allSettled([...inFlight.values()]);
  }
}

/**
 * The synchronous half of the submit door.
 *
 * Order matters here. The job lookup comes FIRST so a request for a job that does
 * not exist costs us nothing: no file written, no row created, and above all no
 * (paid) LLM call. Only once the job is real do we commit anything to disk or to
 * the database (doc 05).
 *
 * @param {object} params
 * @param {number} params.jobId from the URL, shape already checked by the guard
 * @param {{buffer: Buffer, size: number, kind: 'pdf'|'docx'}} params.file the guard's output
 * @param {string} params.callbackUrl where to POST the outcome
 * @returns {Promise<{evaluationId: number, status: string}>} what the 202 carries
 * @throws {NotFoundError} the job does not exist -> the controller's 404
 */
async function startEvaluation({ jobId, file, callbackUrl }) {
  const job = await jobRepository.getJobById(jobId);
  if (!job) throw new NotFoundError(`Job ${jobId} not found`);

  // The original file is kept for the record (doc 02). The name is generated by
  // fileStorage; the uploaded one was dropped by the guard and never touches disk.
  const stored = await fileStorage.saveResumeFile(file.buffer, file.kind);

  const evaluation = await evaluationRepository.createEvaluation({ jobId, callbackUrl });

  // Deliberately NOT awaited: this is the point where the request and the work part
  // company. The promise is parked in `inFlight` so it is still waitable, and its
  // rejection is swallowed here because runPipeline already records every failure on
  // the row - an unhandled rejection would only crash the process for nothing.
  const run = runPipeline({ evaluation, job, stored, fileKind: file.kind, buffer: file.buffer })
    .catch(() => {})
    .finally(() => inFlight.delete(evaluation.id));
  inFlight.set(evaluation.id, run);

  return { evaluationId: evaluation.id, status: evaluation.status };
}

/**
 * The background half: the actual pipeline.
 *
 * Every step that can fail throws a PipelineError carrying doc 06's reason, and one
 * catch turns any of them into a `failed` row with that reason stored. The webhook
 * then fires in `finally`, because the caller must hear back on BOTH outcomes.
 *
 * @returns {Promise<object>} the final evaluation row (completed or failed)
 */
async function runPipeline({ evaluation, job, stored, fileKind, buffer }) {
  let finalEvaluation;
  let candidate = null;

  try {
    // STEP 1 - parse. No LLM: a library reads the file, and an empty result means
    // a scanned or unreadable resume, which we reject rather than OCR (doc 06).
    const text = await parseService.extractText(buffer, fileKind);

    // STEP 2 - extract (LLM call #1). The only time the raw resume text is sent
    // anywhere. From here on we work on clean lists.
    const extracted = await extractionService.extract(text);

    // The candidate record exists as soon as we have candidate facts. Linking it to
    // the evaluation immediately means a failure in a LATER step still leaves HR
    // with a name and a phone number instead of an anonymous failed row.
    const resume = await resumeRepository.createResume({
      ...extracted,
      filePath: stored.filePath,
      extractedText: text,
    });
    await evaluationRepository.updateEvaluation(evaluation.id, { resumeId: resume.id });
    candidate = { name: resume.name, email: resume.email, phone: resume.phone };

    // STEP 3 - match (LLM call #2 for skills, code for experience), with the
    // evidence-grounding check that rejects hallucinated matches.
    const matched = await matchingService.match(extracted, job);

    // STEP 4 - score. Pure code: weights, both gates, and a percentage that is
    // stored even when a gate eliminates the candidate.
    const scored = scoringService.score(matched, job);

    // The result is written to OUR database before anyone is told about it. This is
    // the safety net: even if the webhook never lands, the row is complete and can
    // be read back (doc 06).
    finalEvaluation = await evaluationRepository.updateEvaluation(evaluation.id, {
      status: 'completed',
      failureReason: null,
      eligible: scored.eligible,
      overallPercentage: scored.overallPercentage,
      matchedRequiredSkills: matched.matchedRequiredSkills,
      missingSkills: matched.missingSkills,
      extraSkills: matched.extraSkills,
      requiredExperienceYears: matched.requiredExperienceYears,
      candidateExperienceYears: matched.candidateExperienceYears,
    });
  } catch (err) {
    // A PipelineError already knows why it failed. Anything else is a bug on our
    // side, and is recorded as exactly that rather than blamed on the resume.
    const failureReason =
      err instanceof PipelineError ? err.failureReason : FAILURE_REASONS.INTERNAL;

    if (!config.isTest && !(err instanceof PipelineError)) {
      // eslint-disable-next-line no-console
      console.error(`[pipeline] evaluation ${evaluation.id} failed unexpectedly:`, err);
    }

    finalEvaluation = await evaluationRepository.updateEvaluation(evaluation.id, {
      status: 'failed',
      failureReason,
    });
  }

  // STEP 5 - deliver, on both outcomes. deliver() never throws; a webhook the caller
  // could not receive is recorded, not escalated into an evaluation failure.
  const payload = webhookService.buildPayload(
    finalEvaluation,
    finalEvaluation.status === 'completed' && candidate ? { candidate } : {}
  );
  const delivery = await webhookService.deliver(evaluation.callbackUrl, payload);

  return evaluationRepository.updateEvaluation(evaluation.id, {
    deliveryStatus: delivery.deliveryStatus,
  });
}

// listByJob / getById arrive in Phase 4 with the read doors.
module.exports = { startEvaluation, runPipeline, awaitPendingRuns, inFlight };
